"""initial migration

Revision ID: 46abafbcb0ea
Revises: 9707ab09f121
Create Date: 2017-02-08 21:27:56.770662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46abafbcb0ea'
down_revision = '9707ab09f121'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
