"""initial migration

Revision ID: eeacd19a7e25
Revises: 7c3e3c73ba90
Create Date: 2017-02-10 01:29:54.823329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeacd19a7e25'
down_revision = '7c3e3c73ba90'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img')
    ### end Alembic commands ###
